# Generated by Django 5.0.7 on 2024-10-06 14:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_like_answer_remove_like_owner_delete_dislike_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnswerComment',
            new_name='Comment',
        ),
    ]
